// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqpajiresjojalekozki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxcGFqaXJlc2pvamFsZWtvemtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTUxNTIsImV4cCI6MjA3MDkzMTE1Mn0.wVEtIOF5IPCndm7PBPXqjx5taYbqUrFnRv-QrmAFK8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});